baseURL: http://jauu.net/
languageCode: en-us
title: Just Another Unix User
theme: 'PaperModHgn'

defaultContentLanguage: en
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
enableGitInfo: true

minify:
    disableXML: true
    minifyOutput: true

menu:
    main:
        - identifier: Blog
          name: Blog
          url: archives
          weight: 5
        - identifier: "about"
          name: "About"
          title: "About"
          url: "/about/"
          weight: 10
        - identifier: "talks"
          name: "Talks"
          title: "Talks"
          url: "/talks/"
          weight: 30
        - identifier: search
          name: Search
          url: search/
          weight: 40
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 50

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    disableThemeToggle: true
    fingerprint: "sha512"
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "" #Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Hagen Paul Pfeifer
    # author: ["Me", "You"] # multiple authors
    # can also be dark, but auto is browser based
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    disableShare: True
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    TocOpen: false
    # comments: false
    #images: ["papermod-cover.png"]

      #homeInfoParams:
        #Title: "Hi!"
        #Content: >
        #  Welcome to my personal Space
        #  Cyber-Security Researcher and Developer having interests in
        #  Application-Security, *nix based Systems, Android, Reverse
        #  Engineering and Programming; loves Command Line, FOSS. Read more..


    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: false
        customCSS: ["css/custom.css"]
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  series: series
  tag: tags

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

          # privacy:
          #     vimeo:
          #         disabled: false
          #         simple: true
          # 
          #     twitter:
          #         disabled: false
          #         enableDNT: true
          #         simple: true
          # 
          #     instagram:
          #         disabled: false
          #         simple: true
          # 
          #     youtube:
          #         disabled: false
          #         privacyEnhanced: true
          # 
